services:
  sqlserver:
    build: ./docker/sqlserver
    container_name: rust-cast-sql-sever
    mem_limit: 2G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    environment:
      - MSSQL_USER=${DB_USER}
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver:/var/opt/mssql
    ports:
      - '${DB_PORT:-1433}:1433'
    healthcheck:
      test:
        [
          'CMD-SHELL',
           '/opt/mssql-tools18/bin/sqlcmd -C -U "${DB_USER}" -P "${DB_PASSWORD}" -Q "SELECT 1"',
        ]
      interval: 10s
      retries: 5
      timeout: 3s

  redis:
    build: ./docker/redis
    container_name: rust-cast-redis-cache
    restart: always
    mem_limit: 2.5G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    volumes:
      - redis:/data
    ports:
      - ${REDIS_CACHE_PORT:-27002}:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      retries: 5
      timeout: 3s

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: rust-cast-azurite
    restart: always
    mem_limit: 1G
    memswap_limit: 2G
    cpus: 1
    environment:
      - AZURITE_ACCOUNTS=${AZURITE_ACCOUNT_NAME}:${AZURITE_ACCOUNT_KEY}
    ports:
      - '${AZURITE_BLOB_PORT:-10000}:10000'
      - '${AZURITE_QUEUE_PORT:-10001}:10001'
      - '${AZURITE_TABLE_PORT:-10002}:10002'
    volumes:
      - azurite:/data
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:10000/devstoreaccount1 || exit 1']
      interval: 30s
      retries: 3
      timeout: 10s

volumes:
  redis:
    driver: local
  sqlserver:
    driver: local
  azurite:
    driver: local
