[package]
name = "admin_api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Dependências específicas para a admin_api, como axum, tokio, etc.
axum = "0.7.5"
tokio = { version = "1.0", features = ["full"] }